---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: write-deployment-cportal-role 
  namespace: insurtech
rules:
- apiGroups: ["*"]
  resources: ["deployments"] ### Restrict access for deployment only
  verbs: ["get","watch","list","patch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cportal-write-deployment
  namespace: insurtech
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: write-deployment-cportal-role
subjects:
- kind: Group
  namespace: insurtech
  name: 989a70b0-6b9c-4e3d-96be-ec74bfeb3949