kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: read-insqa2-role 
  namespace: insqa2
rules:
- apiGroups: ["*"]
  resources: ["pods", "pods/log", "configmaps", "events", "nodes", services", "endpoints", "deployments"] ### Restrict access
  verbs: ["get","watch","list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: insqa2-rolebinding
  namespace: insqa2
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: read-insqa2-role
subjects:
- kind: Group
  namespace: insqa2
  name: 763917f8-48fd-44e6-bb64-edc2641bff41