kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: read-cportal-role 
  namespace: insurtech
rules:
- apiGroups: ["*"]
  resources: ["pods", "pods/log", "configmaps", "events", "nodes", services", "endpoints", "deployments"] ### Restrict access
  verbs: ["get","watch","list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cportal-rolebinding
  namespace: insurtech
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: read-cportal-role
subjects:
- kind: Group
  namespace: insurtech
  name: 989a70b0-6b9c-4e3d-96be-ec74bfeb3949