---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: write-deployment-insdemo-role 
  namespace: insdemo
rules:
- apiGroups: ["*"]
  resources: ["deployments"] ### Restrict access for deployment only
  verbs: ["get","watch","list","patch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: insdemo-write-deployment
  namespace: insdemo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: write-deployment-insdemo-role
subjects:
- kind: Group
  namespace: insdemo
  name: d1f1854a-da39-443a-b80e-7399cac29742