kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: adminclusterrole ### Admin role
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: adminclusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: adminclusterrole
subjects:
- kind: Group
  name: c702fb0f-7f02-4296-8ed8-2662e531e347 ### ObjectID for Dev AKS Admins  