kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: read-ingress-role
  namespace: ingress
rules:
- apiGroups: ["*"]
  resources: ["pods", "pods/log", "configmaps", "events", "nodes", services", "endpoints", "deployments"] ### Restrict access
  verbs: ["get","watch","list"]